### ISSUE TITLE
[Question] why file/url loader

### ISSUE THREAD

**Issue by Kikobeats** [tachyons-css/tachyons-webpack#4]
I'm talking about this loaders: https://github.com/tachyons-css/tachyons-webpack/blob/master/webpack.config.js#L28-L53

When I compile the build locally, nothing happens. I mean, it doesn't create a `font` folder, is that the expected behavior?

**Comment by garrensmith** [comment]
Its not meant to create a fonts folder. If you have one, it will add those fonts into the build.

**Comment by Kikobeats** [comment]
👍
